default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: ejpayne
  password:

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  url: <%= ENV["postgres://kanflmcszabuhn:NfwyNlQKJZhaPw647y7EtEqCTF@ec2-54-197-238-19.compute-1.amazonaws.com:5432/ddm0t0f587s33o"] %>