development:  
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: ejpayne
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: ejpayne
  password:
